# Generated by Django 3.2.9 on 2021-11-12 15:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import privacydates.fields
import privacydates.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('privacydates', '0002_auto_20211026_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('rough_date', privacydates.fields.RoughDateField(blank=True, default=django.utils.timezone.now, null=True, reduction_value=30)),
                ('ordering_date', privacydates.fields.OrderingDateField(blank=True, null=True, similarity_distance=0)),
                ('ordering_similarity_date', privacydates.fields.OrderingDateField(blank=True, null=True, similarity_distance=2)),
                ('vanishing_date', privacydates.fields.VanishingDateField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='privacydates.vanishingdatetime')),
                ('vanishing_ordering_date', privacydates.fields.VanishingDateField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='privacydates.vanishingdatetime')),
            ],
            bases=(models.Model, privacydates.mixins.VanishingDateMixIn),
        ),
    ]
