# Generated by Django 3.1.4 on 2021-06-24 08:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import privacydates.fields
import privacydates.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('privacydates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('generalized_date', privacydates.fields.GeneralizationField(blank=True, default=django.utils.timezone.now, null=True, reduction_value=30)),
                ('enumeration_date', privacydates.fields.EnumerationField(blank=True, null=True, similarity_distance=0)),
                ('enumeration_similarity_date', privacydates.fields.EnumerationField(blank=True, null=True, similarity_distance=2)),
                ('annihilation_date', privacydates.fields.AnnihilationField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='privacydates.datetimeannihilation')),
                ('annihilation_enumeration_date', privacydates.fields.AnnihilationField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='privacydates.datetimeannihilation')),
            ],
            bases=(models.Model, privacydates.mixins.AnnihilationMixIn),
        ),
    ]
